### ISSUE TITLE
[EXEMPLO] Como deixar os itens da lista um do lado do outro?

### ISSUE THREAD

**Issue by yogmel** [reprograma/html-css-basico#2]
No meu arquivo HTML, ele está assim: 
 ```
<nav>
    <a href="#"><img src="img/logo.png"></a>
    <ul class="menu">
        <li><a href="#">Home</a></li>
        <li><a href="#">Sobre</a></li>
        <li><a href="#">Contato</a></li>
    </ul>
</nav>
```

E no meu CSS:
```
nav {
    position: fixed;
    top: 0;
    width: 100%;
}
.menu {
    display: inline-block;
}
```

Estou usando o Chrome, em um Windows.

HEWLP!!!

**Comment by thayllachristine** [comment]
@yogmel, posso fechar essa issue?

**Comment by yogmel** [comment]
@thayllachristine claro florzinha :)

**Comment by LeticiaCamelloBarros** [comment]
como fazer isso em uma lista python ? quero printar os itens de uma lista um do lado do outro sendo que não quero a virgula nem o colchete que aparece quando se pede para printar uma lista

**Comment by yogmel** [comment]
Oi @LeticiaCamelloBarros , o que você quer dizer com "uma lista Python"? Qual o formato dessa lista?

**Comment by LeticiaCamelloBarros** [comment]
> Oi [@LeticiaCamelloBarros](https://github.com/LeticiaCamelloBarros) , o que você quer dizer com "uma lista Python"? Qual o formato dessa lista?
uma lista tipo assim : 

lista = ["sal","trigo","farinha","manteiga"] 
 
queria printa-la dessa forma : 
 
sal , farinha , trigo , manteiga

**Comment by yogmel** [comment]
@LeticiaCamelloBarros pra fazer uma lista dinâmica, HTML e CSS não é suficiente, você tem que usar Javascript. Um exemplo seria:
```html
<html>
  <div>
    <ul id="lista"></ul>
  </div>

  <script>
    // seleciona o elemento ul com o id "lista"
    const ul = document.getElementById("lista");
    // guarda sua lista dentro de uma variável
    const itemsLista = ["sal", "trigo", "farinha", "manteiga"];

    // laço que roda o número de vezes da lista
    for (let i = 0; i < itemsLista.length; i++) {
      // cria um elemento li
      const li = document.createElement("li");
      // adiciona o texto da lista no elemento li
      li.textContent = itemsLista[i];
      // adiciona o elemento li na ul
      ul.appendChild(li);
    }
  </script>
</html>

```
